@startuml

class Shoe {
Long shoeCode
String shoeName
String color
int size
BigDecimal price
+ _create()
}

enum OrderStatus {
NORMAL
CANCELLED
}

class Order {
Long orderNo
OrderStatus status
List<OrderDetail> details
List<String> paymentIds
+ _create()
+ totalCancel()
+ partialCancel()
+ updatePaymentIds()
+ getCurrentTotalAmount()
+ getAmountToCancel()
- validateAvailableCancel()
- validateAllCancelled()
}

class OrderDetail {
Long orderDetailNo
OrderStatus orderDetailStatus
String shoeProductCode
BigDecimal unitPrice
Long count
+ getShoeCode()
+ _create()
# totalCancel()
# partialCancel()
+ isNormal()
+ isCancel()
}

enum PaymentType {
CASH
CREDIT_CARD
}

enum CreditCardType {
SHINHAN
SAMSUNG
KB_KOOKMIN
HYUNDAI
LOTTE
WOORI
HANA
BC
}

abstract class Payment {
String id
PaymentType type
BigDecimal paidAmount
# updatePaidAmount()
+ updatePaidAmountToZero()
+ validateAvailableCancel()
+ partialCancel()
}

class CashPayment {
+ _payInCash()
}

class CardPayment {
CreditCardType creditCardType
+ _payInCreditCard()
}

class Inventory {
Long shoeCode
LocalDate stockedDate
Long stock
+ _create()
+ restock()
+ deductStock()
- validateRequestStock()
}

Order <-- OrderDetail
Payment <-- CashPayment
Payment <-- CardPayment
Inventory -- Shoe

@enduml