@startuml

class Shoe {
Long shoeCode
String shoeName
String color
int size
BigDecimal price
+ create()
}

enum OrderStatus {
NORMAL
CANCELLED
}

class Order {
Long orderNo
OrderStatus orderStatus
List<OrderDetail> details
BigDecimal totalAmount
List<OrderPayment> payments
+ create()
+ totalCancel()
+ partialCancel()
- validateAvailableCancel()
- validateAllCancelled()
}

class OrderDetail {
Long orderDetailNo
OrderStatus orderStatus
Long shoeCode
Long count
+ create()
* partialCancel()
+ isNormal()
+ isCancelled()
}

class OrderPayment {
PaymentType paymentType
CreditCardType creditCardType
BigDecimal paidAmount
+ payInCash()
+ payInCreditCard()
+ partialCancel()
}

enum PaymentType {
CASH
CREDIT_CARD
}

enum CreditCardType {
SHINHAN
SAMSUNG
KB_KOOKMIN
HYUNDAI
LOTTE
WOORI
HANA
BC
}


Order <-- OrderDetail
Order <-- OrderPayment

@enduml